In [1]:
import pandas as pd
import os

In [9]:
reco_file_dir = "../Final_Recommendation_Letters/"
candidates = pd.read_csv("../Final_Resume_Texts/resume_with_actual_roles.csv")
# add a lor field to the candidates dataframe
candidates["lor_data"] = ""
# add a lor_from field to the candidates dataframe with empty list
candidates["lor_from"] = [[] for i in range(len(candidates))]
for i in range(len(candidates)):
    
    reco_data = ""
    id = candidates.loc[i, "id"]
    # in the folder, sub folder of the form Recommendation_Letters_of_ID_1
    # files are of the form Recommendation_From_ID_2.txt
    reco_file_sub_dir = reco_file_dir + "Recommendation_Letters_of_ID_" + str(id) + "/"
    # if the folder does not exist, skip
    if not os.path.exists(reco_file_sub_dir):
        continue
    for letter in os.listdir(reco_file_sub_dir):
        with open(reco_file_sub_dir + letter, "r", encoding="windows-1250") as f:
            reco_data += f.read()
        candidates.loc[i, "lor_from"].append(int(letter.split("_")[-1].split(".")[0]))
    candidates.loc[i, "lor_data"] = reco_data

candidates.head()

,Unnamed: 0,id,title,text,role_raw,role,lor_data,lor_from
0,0,0,bilingual language arts sixth grade teacher,BILINGUAL LANGUAGE ARTS SIXTH GRADE TEACHER\r\...,bilingual language arts sixth grade teacher,Bilingual Language Arts Teacher,The connection between the roles of the two in...,"[218, 391]"
1,1,1,mortgage banking default operations specialist ii,MORTGAGE BANKING DEFAULT OPERATIONS SPECIALIST...,mortgage banking default operations specialist ii,Mortgage Banking Operations Specialist,Based on extensive experience in project coord...,"[233, 289, 412, 869]"
2,2,10,operations manager,OPERATIONS MANAGER\r\nSummary\r\nExperienced c...,operations manager,Operations Manager,Having worked as an HR Employee Relations Spec...,"[481, 955, 962]"
3,3,100,president/chief executive officer,PRESIDENT/CHIEF EXECUTIVE OFFICER\r\nExecutive...,president/chief executive officer,Chief Executive Officer,As a Senior Application Specialist with a robu...,[424]
4,4,101,chief executive officer,CHIEF EXECUTIVE OFFICER\r\nSummary\r\nAward-wi...,president/chief executive officer,Chief Executive Officer,"As the Director of Finance, I am pleased to re...","[24, 318, 482, 882]"

In [10]:
candidates.to_csv("../Final_Resume_Texts/resume_with_actual_roles_and_lor.csv", index=False)